import { Router } from 'express';
import { i18nRouter } from './i18n';
import { transactionRouter } from './transactions';
import { eventRouter } from './events';
import { contractRouter } from './contracts';
import { walletRouter } from './wallets';
import { tokenRouter } from './tokens';
import { authorizationRouter } from './authorizations';
import { renderRouter } from './render';
import { simulateRouter } from './simulate';
import { verifyRouter } from './verify';
import { dexRouter } from './dex';
import { protocolRouter } from './protocol';
import { nftRouter } from './nft';
import { alertsRouter } from './alerts';
import { assetsRouter } from './assets';
import { sseRouter } from './sse';
import { graphRouter } from './graph';
import { virtualListRouter } from './virtualList';
import { tokenMetadataRouter } from './token-metadata';
import { webhooksRouter } from './webhooks';
import { analyticsRouter } from './analytics';
import { portfolioRouter } from './portfolio';
import { exportsRouter } from './exports';
import { syncStateRouter } from './sync-state';
import { yieldDistributionRouter } from './yield-distribution';
import { yieldRouter } from './yield';
import { dtccSettlementRouter } from './dtcc-settlement';
import { commodityComplianceRouter } from './commodity-compliance';
import { settlementBatchRouter } from './settlement-batch';
import { governanceRouter } from './governance';
import { systemicRouter } from './systemic';
import { benchmarkRouter } from './benchmarks';
import { networkRouter } from './network';

export const router = Router();

router.use('/transactions', transactionRouter);
router.use('/events', eventRouter);
router.use('/contracts', contractRouter);
router.use('/wallets', walletRouter);
router.use('/tokens', tokenRouter);
router.use('/authorizations', authorizationRouter);
router.use('/render', renderRouter);
router.use('/simulate', simulateRouter);
router.use('/verify', verifyRouter);
router.use('/dex', dexRouter);
router.use('/protocol', protocolRouter);
router.use('/nft', nftRouter);
router.use('/alerts', alertsRouter);
router.use('/assets', assetsRouter);
router.use('/sse', sseRouter);
router.use('/graph', graphRouter);
router.use('/virtual-list', virtualListRouter);
router.use('/token-metadata', tokenMetadataRouter);
router.use('/webhooks', webhooksRouter);
router.use('/analytics', analyticsRouter);
router.use('/portfolio', portfolioRouter);
router.use('/exports', exportsRouter);
router.use('/sync-state', syncStateRouter);
router.use('/yield-distributions', yieldDistributionRouter);
router.use('/yield', yieldRouter);
router.use('/dtcc-settlement', dtccSettlementRouter);
router.use('/commodity-compliance', commodityComplianceRouter);
router.use('/settlement-batch', settlementBatchRouter);
router.use('/governance', governanceRouter);
router.use('/systemic', systemicRouter);
router.use('/benchmarks', benchmarkRouter);
router.use('/network', networkRouter);
